### ISSUE TITLE
Higher level create_sub_buffer call

### ISSUE THREAD

**Issue by vmx** [kenba/opencl3#13]
The current sub buffer API is quite low level. I'd like to see a higher level API that needs less imports and boilerplate code. My code currently looks like that:

```rust
use std::ffi::c_void;
use opencl3::memory::{CL_MEM_READ_WRITE, CL_BUFFER_CREATE_TYPE_REGION};
use opencl3::types::cl_buffer_region;

let buffer_create_info = cl_buffer_region {
    origin: offset * std::mem::size_of::<T>(),
    size: data.len() * std::mem::size_of::<T>(),
};
let buff = buffer.buffer.create_sub_buffer(
    CL_MEM_READ_WRITE,
    CL_BUFFER_CREATE_TYPE_REGION,
    &buffer_create_info as *const _ as *const c_void,
)?;
```

The `buffer_create_type` is always `CL_BUFFER_CREATE_TYPE_REGION` according to the [current OpenCL spec](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#subbuffer-create-info-table) and I also find the need for the pointer casting a bit too low level. I propose a function signature like:

```rust
pub fn create_sub_buffer(
    &self,
    flags: cl_mem_flags,
    origin: usize,
    count: usize,
) -> Result<Buffer<T>>
```

So the above code would then just be:

```rust
use opencl3::memory::{CL_MEM_READ_WRITE};

let buff = buffer.buffer.create_sub_buffer(
    CL_MEM_READ_WRITE,
    origin: offset,
    count: data.len(),
)?;
```

**Comment by kenba** [comment]
Good call Volker! Yes that interface makes no sense at this level, especially considering that there is only one value for `cl_buffer_create_type`!

I've implemented the interface you propose in the `develop` branch. I plan to update `opencl3` to version `0.3.0` sometime soon and I'll publish this change then.

**Comment by vmx** [comment]
Thanks that's great. The code works for me.
