### ISSUE TITLE
Restore `c_void` to program.rs

### ISSUE THREAD

**Issue by jleflang** [kenba/opencl3#20]
There is a compilation error due to `c_void` not being in-scope in program.rs when the `CL_VERSION_2_2` feature is enabled. It  was removed after #12 was resolved.

**Comment by kenba** [comment]
Sorry about that James.
I've just updated it in the `develop` branch. Please can you confirm that the fix works for you?

**Comment by jleflang** [comment]
That fixes this issue. Thank you!
