### ISSUE TITLE
Should `CommandQueue.html::enqueue_write_buffer` take a mutable buffer reference?

### ISSUE THREAD

**Issue by vmx** [kenba/opencl3#26]
I currently work on abstraction to make code work with both OpenCL and CUDA. The CUDA library I'm using ([RustaCUDA](https://github.com/bheisler/RustaCUDA) has a [similar Buffer abstraction](https://docs.rs/rustacuda/0.1.3/rustacuda/memory/struct.DeviceBuffer.html) as `opencl3`.

When copying data into the device memory, the CUDA library considers the buffer to be mutable. That make sense to me, when I think about Rust semantics. The buffer on the device is mutated. Hence my question: would it make sense to change the API of [`CommandQueue.html::enqueue_write_buffer`](https://github.com/kenba/opencl3/blob/1107b20de775919c18c8c88612d95d7d3ed1ab21/src/command_queue.rs#L235-L242) to take a mutable `Buffer` reference?

**Comment by kenba** [comment]
Yes Volker that makes sense.
Would you like to submit a PR for it?
