### ISSUE TITLE
Superfluous/Misleading generic parameter in `ExecuteKernel::set_arg_local_buffer`

### ISSUE THREAD

**Issue by KarelPeeters** [kenba/opencl3#35]
Currently `ExecuteKernel::set_arg_local_buffer` has  a generic type parameter `T`. Even though it's never actually used. Initially I thought this meant the size was the length of the buffer (with the given data type), but it's indeed the size in bytes.

I think this generic parameter can just be removed.

https://github.com/kenba/opencl3/blob/f8f972e9a65899656e6cd03669f039b8f74976e0/src/kernel.rs#L368-L389

**Comment by kenba** [comment]
Agreed, generic type parameter removed on develop branch.

**Comment by KarelPeeters** [comment]
Great, thanks!
