### ISSUE TITLE
Implement Serde's Serialize, Deserialize for SvmVec

### ISSUE THREAD

**Issue by kenba** [kenba/opencl3#37]
The Rust API Guidelines recommend that "Types that play the role of a data structure should implement [Serialize](https://docs.serde.rs/serde/trait.Serialize.html) and [Deserialize](https://docs.serde.rs/serde/trait.Deserialize.html)", see: [C-SERDE](https://rust-lang.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde). Therefore, SvmVec should implement the serde `Serialize` and `Deserialize` traits.

**Comment by kenba** [comment]
I have been able to implement `Serialize for SvmVec`. However, I cannot determine how to implement `Deserialize for SvmVec` because the [Deserialize](https://docs.serde.rs/serde/trait.Deserialize.html) method signature *only* takes a `Deserializer` parameter. However, it needs to take an additional `Context` parameter to allocate the `SvmVec` memory.

Has anyone got any ideas how to implement `Deserialize for SvmVec`?

**Comment by jkelleyrtp** [comment]
I believe you want https://docs.serde.rs/serde/de/trait.DeserializeSeed.html

**Comment by kenba** [comment]
Thank you Jonathan, `DeserializeSeed` looks perfect!

**Comment by kenba** [comment]
Added `ExtendSvmVec` DeserializeSeed implementation for `SvmVec` and `opencl2serde.rs` example file in version `0.6.2` of the library.
