### ISSUE TITLE
One question related to provided example

### ISSUE THREAD

**Issue by itzmeanjan** [kenba/opencl3#45]
Hello,

I was going through example provided [here](https://github.com/kenba/opencl3/blob/a3c6df0fd2b2ce52aecd302d685b612168e0996b/examples/basic.rs#L72-L76) and noticed buffer `x`, `y` are created with flag `CL_MEM_WRITE_ONLY` while `z` created with flag `CL_MEM_READ_ONLY`, although in [kernel](https://github.com/kenba/opencl3/blob/a3c6df0fd2b2ce52aecd302d685b612168e0996b/examples/basic.rs#L25-L33) `z` is the one buffer which is being modified. I also checked how arguments to kernel are set [here](https://github.com/kenba/opencl3/blob/a3c6df0fd2b2ce52aecd302d685b612168e0996b/examples/basic.rs#L92-L94). Finally I noticed one [copy back to host](https://github.com/kenba/opencl3/blob/a3c6df0fd2b2ce52aecd302d685b612168e0996b/examples/basic.rs#L107) which just reads from buffer `z`.

I was hoping to see it as below

```
x, y -> CL_MEM_READ_ONLY
z -> CL_MEM_WRITE_ONLY
```

following OpenCL [specification](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_buffer_objects)'s first three rows of Table 12.

Am I missing something @kenba ?

**Comment by kenba** [comment]
Well spotted Anjan!

I have indeed got the `CL_MEM_WRITE_ONLY` and `CL_MEM_READ_ONLY` flags the wrong way round.  I'm surprised that it worked!  
I shall fix them in `basic.rs` and in `integration_test.rs`.

Thanks
Ken

**Comment by itzmeanjan** [comment]
> I'm surprised that it worked!

Yes, I also wrote one similar kind of example and it worked fine for me. 

> I shall fix them in `basic.rs` and in `integration_test.rs`.

Thanks @kenba 

I'm closing this issue.
