### ISSUE TITLE
Query related to Intel support changes release/tag

### ISSUE THREAD

**Issue by kballeda** [kenba/opencl3#61]
Hi @kenba, Following PR  https://github.com/filecoin-project/rust-gpu-tools/pull/83 on rust-gpu-tools uses changes that we published recently on opencl3/develop branch. There is a dependency between opencl3 and rust-gpu-tools, can you please help us in creating tag for it so that rust-gpu-tools works smoothly?

**Comment by kenba** [comment]
Repo now tagged at version `0.9.3` and published to `crates.io`.

**Comment by kballeda** [comment]
> Repo now tagged at version `0.9.3` and published to `crates.io`.

Thanks a lot !
