### ISSUE TITLE
Unsound issue in SvmVec

### ISSUE THREAD

**Issue by CXWorks** [kenba/opencl3#69]
Hi, thanks for your time to read this issue. Our static analysis tool found there might be an unsound issue in your `set_len` implementation of buffer:

https://github.com/kenba/opencl3/blob/1d7d74da2ff76c93c7418dd016386a8b907e2bd3/src/svm.rs#L300-L311

As mentioned in the comments, this may introduce uninitilaized memory and reading it is considered as undefined behavior in Rust. As a reference, in std library, all the `set_len` method are marked as unsafe:

https://github.com/rust-lang/rust/blob/63a0bdd5622eaf6b9524702f055bb4525acfc9f2/library/alloc/src/vec/mod.rs#L1849-L1853

Thanks again for your time.

**Comment by kenba** [comment]
Change incorporated in version `0.10.0`.
